# Generated by Django 5.0.1 on 2024-02-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_user_reset_password_token'),
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitmodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.user'),
            preserve_default=False,
        ),
    ]
