# Generated by Django 5.0.1 on 2024-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=100)),
                ('about_me', models.CharField(blank=True, default='', max_length=100)),
                ('website_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('total_upvote_count', models.IntegerField(default=0)),
                ('phone_num', models.CharField(blank=True, max_length=30, unique=True)),
                ('experience_level', models.CharField(choices=[('Student', 'Student'), ('Junior', 'Junior'), ('Mid_Level', 'Mid Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], default='Student', max_length=30)),
            ],
        ),
    ]
