# Generated by Django 5.0.1 on 2024-02-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_remove_question_likes_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_expert',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Expert', 'Expert'), ('Admin', 'Admin')], default='User', max_length=30),
        ),
    ]
